== The Life of Jane Hoskins

A concern having for some time remained on my mind to commemorate
the tender dealings of a merciful God,
in visiting my soul in the days of my youth;
I have endeavoured briefly to set forth the same in the following lines.

I was born in London, the 3rd day of the first month, in the year 1693-4,
of religious parents,
and by them strictly educated in the profession of the church of England, so called; who,
according to the best of their understanding,
endeavoured to inculcate into my mind the knowledge of a Divine Being,
and how necessary it was for all professing Christianity, to live in the fear of God.
But this good advice I too often slighted,
as likewise the blessed reproofs of the holy spirit of Christ in my soul.
Though I was but young, I was, through mercy,
preserved from the commission of gross evils; yet being of a cheerful disposition,
and having a turn to music and singing, I was much delighted therewith,
and was led into unprofitable company, all which had a tendency to lead my mind from God,
for which strong convictions followed me as a swift witness against sin.
But he who had compassion on me from the days of my infancy,
was pleased in the sixteenth year of my age, to visit me with a sore fit of sickness,
nigh unto death, which reduced me very low both in body and mind;
for the terrors of the Almighty took hold of my soul,
and then was brought into my remembrance all my sins and misspent time,
as well as the good counsel my dear parents had tenderly given me,
which I had unhappily disregarded.
In this distressed condition I shed many tears,
making my moan to Him who is the helper of his people in the needful time,
and was ready to make covenant,
that if he in mercy would be pleased to spare me a little longer,
the remaining part of my days should be dedicated to his service;
and it was as though it had been spoken to me, "`if I restore thee, go to Pennsylvania.`"
To which the answer of my soul was, wherever thou pleasest.
This opening appeared strange to me at that time; but all I wanted then,
was peace of mind and health of body.
However, it pleased the Lord to raise me up from this low condition,
and I as soon forgot the promises I had made in deep distress,
and returning again to my old amusements,
endeavoured thereby to stifle the witness of God, which had been raised in me.

But he who in tender mercy strives long with the children of men,
and would not that any should be lost, followed me in judgment, and often when alone,
brought me under great condemnation,
so that I was made to cry for strength to overcome the evils which so easily beset me.
Then Pennsylvania came again into my mind;
but as I was much delighted with outward objects,
and strongly attached to such things as were pleasing to my natural temper,
so the cross of Christ was thereby made great in appearance to me,
and I would reason thus; "`What shall I do in a strange country,
separated from the enjoyments of all my relations and friends?`"
But on a certain time, it was said in my soul, "`Go,
there shalt thou meet with such of my people as will
be to thee in the place of near connections;
and if thou wilt be faithful, I will be with thee.`"
This was spoken to me in such power, that I was broken into tears, and said,
"`Lord I will obey.`"
But I unhappily got over this likewise,
and so remained until the visitation from on high was again extended,
which was like thunder to my soul, and by the light of Christ,
though I knew not then what name to ascribe to it, I was clearly told,
that if I did not comply, I should be forever miserable; wherefore,
I took up a resolution,
and acquainted my parents with the desire I had of going to America;
"`I told them that it seemed as a duty laid upon me,
and that I thought it might be for my good to go, for that by being among strangers,
I might with more freedom serve God, according to their frequent precepts to me.`"
I remember the remark my father made on these arguments, was,
"`the girl has a mind to turn Quaker.`"
I said, "`I hope I shall never renounce my baptism.`"

He charged me never to speak any more about it, for he would never consent to my going;
his will was as a law to me, and therefore I concluded to obey him,
making myself for the present easy,
with having so far endeavoured to comply with the heavenly requiring.
But it did not last long, Pennsylvania was still in my mind, the thought continued,
that if I was among strangers, I could better serve God,
though I had no thought of leaving the profession I was brought up in,
nor had I any acquaintance with Friends or knowledge of their principles.
But my friends were all averse to my going,
and my mother took occasion to lay before me the danger and difficulties
one of my years and circumstances might be subjected to,
in such an undertaking, which had such weight with me, that I was again diverted from it.
After some time I grew very uneasy, insomuch that sleep departed from me,
and the weight of the exercise was so great,
that I was made willing to forego everything else,
to pursue what I believed to be my duty, and concluded, that whatever I suffered,
I would not delay any longer, but embrace the first opportunity of going to Pennsylvania,
provided the Almighty would go with me, and direct my steps,
which like a little child I humbly begged he might be graciously pleased to do.
In a little time the way opened.
One Robert Davis, a Welchman, with his wife and two daughters,
were going to settle in Philadelphia; a friend told me of their going,
and went with me to them; we soon agreed, that he should pay for my passage,
and wait until I could earn the money on the other side of the water,
for which he accepted of my promise without note or bond,
or my being bound by indenture in the usual manner.

Under these circumstances I came into this land, and have great cause,
with reverence and fear, to bless the name of the Lord, whose good hand did, I believe,
direct in this weighty undertaking.
We arrived in Philadelphia the 16th day of the third month, 1712,
in the nineteenth year of my age.
As soon as I was landed I was provided with a place, among people of repute,
of my own society.

As I had not gone into this undertaking in my own will, or to fly from the cross,
but in a degree of obedience to the will of my heavenly Master and Father,
and much in the cross, so now I felt his good presence near to me;
and an eye being opened in me toward him, I became weaned from the gaities,
pleasures and delights of this fading world; they were all stained in my view,
and an ardent thirst to partake of the waters of
life and salvation of God took place in my mind.
I loved solitude--sought retirement--and embraced
all opportunities of attending Divine service,
so called, having free liberty from those among whom I lived so to do,
they being very kind to me;
but still I found not that solid peace and satisfaction to my seeking soul,
which I wanted.
The reason hereof, as I have since experienced, was,
because I sought the living among the dead, as too many do; and the enemy of all good,
was still unwearied in his attempts against me.
Having learned in my native country to sing, he stirred up those with whom I now lived,
to draw me into that vain amusement, which, as I plainly saw it was a snare of his,
it brought trouble and uneasiness over my mind.

After I had been in Philadelphia somewhat more than a quarter of a year,
Robert Davis insisted I should sign indentures, binding myself a servant for four years,
to a person who was an utter stranger to me,
by which means he would have made considerable advantage to himself.
But as this was contrary to our agreement before-mentioned,
which I was willing to comply with to the utmost of my power,
and as a remarkable uneasiness and deep exercise attended my mind,
when I endeavoured to comply with his mercenary will,
I thought it best to withstand him in it, let the consequence be what it would;
whereupon he had recourse to the law, and by process laid me under confinement.
This was a trying circumstance.
I was a poor young creature among strangers,
and being far separated from my natural friends,
they could not redress my grievances nor hear my complaints.

But the Lord heard my cries and raised me up many friends,
who visited me in this situation and offered me money to pay Davis for my passage,
according to contract, but I could not accept even of this kindness,
because I was well assured Philadelphia was not to be the place of my settlement,
though where I was to go was yet hid from me; however, as I endeavoured to wait,
the Lord provided for me after this manner.
The principals of four families living at Plymouth, who had several children,
agreed to procure a sober young woman, as a school-mistress to instruct them in reading, etc.
And on their applying to their friends in town, I was recommended for that service.
When we saw each other, I perceived it my place to go with them; wherefore,
on their paying Davis twelve pounds currency, being the whole of his demand against me,
I bound myself to them by indenture, for the term of three years,
and went cheerfully with them to the aforesaid place.
And I have thought how wonderful it was, that though various scenes attended me,
yet I was enabled to perform the service they had for me.
The children learned very fast,
which afforded comfort to me and satisfaction to their parents;
my love to them was great, and theirs equally so to me,
so that all my commands were obeyed with pleasure,
and when we met could tell one another of it with sincere regard and affection.
They proved sober, religious men and women.

I served my time faithfully, and never had cause to repent it;
the people with whom I lived, were those called Quakers,
and as I had not been among any of that denomination before,
I had desires in my mind to be acquainted with their principles, and manner of worship,
and having liberty, was very ready to go to their meetings,
though at first only as a spy; but after I had been some time among them,
and took notice of their way and manner of performing Divine worship to God,
I was ready to conclude and say in my mind, surely these are his people; and a brave,
living people they really were; there being divers worthies among them,
who I believe are now in the fruition of joy unspeakable, and full of glory,
the earnest of which, they through mercy then at times partook of,
to the satisfaction of their hungry and thirsty souls.
The solid, weighty and tender frame of spirit some of them were many times favoured with,
in meetings, brought serious considerations over my mind, with this query:
Why is it not so with me?
And I said in my heart, these people are certainly better than I am,
notwithstanding I have made a great deal more to do about religion than they.

As I was pondering on these things, the saying of the apostle,
"`that circumcision or uncircumcision avails nothing,
but a new creature in Christ Jesus,`" was often brought to my mind.
I saw this work must begin in the heart, and be carried on by a Divine power.
This I was soon convinced of, and therefore could wait with patience, though in silence.
But yet the whole work was not completed, it went on gradually, step by step,
which demonstrates the paternal care of our heavenly Father,
carrying the lambs in his arms, lest they should be weary and faint!
Who can but admire his goodness, and celebrate his praise?
His wisdom and power are great.
Oh! that all would but dwell under his peaceable government, and learn of him,
who is pure and holy.
Through the operation of Divine Goodness,
great love was begotten in my heart to these people;
and if at any time Friends were concerned to speak against any evil habit of the mind,
I did not put it from me, but was willing to take my part,
and have sometimes thought it all belonged to me.

As I continued in this humble frame, and was diligent in attending meeting when I could,
Infinite Goodness was graciously pleased to favour me with
a fresh and large visitation of his heavenly love,
and often tendered my spirit and begot strong desires after true and saving knowledge,
and that the way of life and salvation might be clearly demonstrated;
and blessed be his eternal name,
he heard my cries and was pleased to send his servants both male and female,
filled with life and power, who sounded forth the Gospel in Divine authority,
declaring the way to the Father through the door of Christ,
and opening the principles of these people,
by turning our minds inward to the pure gift and manifestation of the spirit.

This doctrine agreeing with what I had in some measure been convinced of,
I was made willing to join heartily with it, and was ready to say,
these are true ministers of Christ, for they spoke with Divine power and authority,
and not as the scribes.
Now I was mightily reached unto, and stripped of all self-righteousness,
and my state was opened to me in such a manner, that I was quite confounded,
and concluded that though I could talk of religion, of being made a child of God,
a member of his church, and an inheritor of his holy kingdom,
there was as much need as ever to cry,
Lord have mercy on me a poor sinner! not having yet witnessed
the law of the spirit of life in Christ Jesus,
to set me free from the law of sin and death.
Outward ceremonies availed nothing, the new birth was wanting, and must be witnessed,
in order to prepare me for the work whereunto the Lord had called me,
and was about to engage me in.
The baptism of the spirit was to be known before I could be a member of Christ`'s church;
this great work I saw by Divine favour,
I must submit unto if ever I came to be a partaker of that
bread which nourishes the soul unto eternal life.

But Oh, the weight and exercise I was under during this time of refinement;
the days and nights of godly sorrow and penitential mourning I underwent,
are far beyond my ability to set forth in words; and once being alone I wept exceedingly,
and the desire of my soul was, that it might please the Almighty to show me his ways,
to teach me his paths which lead to peace,
and give me strength to walk therein according to his word;
promising that I would endeavour to follow in the way which was most pleasing to him,
for that was what my panting soul most desired.
My desires were not for great things, but Divine favour;
the Lord alone was become the centre of my happiness,
and I believe I should have died at that time,
had he not been pleased in a wonderful manner to
manifest himself a present help in that needful time,
and to reveal himself through his dear Son Christ Jesus,
by administering consolation to my wounded soul, filling my heart with heavenly love,
so that my cup ran over, and I was made to cry out,
Oh that all may know thee and thy goodness!
His matchless lovingkindness so overcame me,
that I thought I could have gone through the world to proclaim
the tender dealings of a merciful God to my soul.
Here I again renewed my covenant with God, and promised obedience to his commands;
and Oh! the calm, the peace, comfort, and satisfaction wherewith my mind was clothed,
like a child enjoying his father`'s favour, and with inexpressible delight,
beholding the smiles of his countenance.
I was afraid to do or say anything that might offend the Lord,
lest the rod might be laid heavy on me, for this is the portion of disobedience.

In that time I became a wonder to many,
but was treated with great tenderness by most of the Friends and neighbours.
I had laid aside all superfluity of apparel, for which I had been condemned;
I attended meetings diligently, and walked three or four miles to them,
sometimes alone meditating upon the Lord,
and thought the work of my present and future happiness was now completed in me,
that I had nothing to do but sit contented under the enjoyment of Divine favour,
rejoicing that I had left all and followed Christ,
whom I loved more than my natural life.
Thus I concluded in my own mind, not knowing as yet what the Lord was preparing me for,
nor that there was a further work allotted me, which I was a stranger to,
till one time being in a meeting,
and sitting very contented under my own vine and fig-tree, a call arose in my mind,
"`I have chosen thee a vessel from thy youth to serve me,
and to preach the Gospel of salvation to many people; and if thou wilt be faithful,
I will be with thee unto the end of time, and make thee an heir of my kingdom.`"

These words were attended with life and power, and I knew his promises were yea,
and amen forever.
Yet I must confess, this awful word of Divine command shocked me exceedingly,
my soul and all within me trembled at the hearing of it; yea my outward tabernacle shook,
insomuch that many present observed the deep exercise I was under.
I cried in spirit, "`Lord I am weak and altogether incapable of such a task,
I hope thou wilt spare me from such a mortification;
besides I have spoken much against women appearing in that manner.`"
This and more such like reasonings I was filled with, which did not administer peace,
but death and judgment.
Great darkness began to spread over my understanding, and increased to such a degree,
that nothing but horror possessed my soul.
I went to meetings as usual, but I felt not the least enjoyment of the Divine presence,
but on the contrary, inexpressible anguish of mind, so that I could not shed a tear,
and concluded all was over with me, and that I was lost forever.
My very countenance was changed and became a true index of my deep distress,
and a person that I had a great love for,
told me she had the word of the Lord to declare to me, which was,
that I had withstood the day of my visitation, and now was left to myself.
This I readily believed, and so gave over all hope of salvation;
and the grand enemy got in with his temptations and suggestions,
and like a torrent which bears down all before it,
made my sorrow and bitterness of soul inexpressible;
and certainly he had prevailed against me with his wicked devices, had not the Almighty,
by his eternal arm of power, interposed, and drove him back, saying unto me,
in the hour of my deepest probation, "`Be obedient and all shall be forgiven;
and thy soul shall be filled with joy and peace unspeakable.`"
At the hearing of which, I broke out into tears,
and in deep humility blessed his holy arm for delivering me from the mouth of the lion,
who seeks to devour all he can.
I renewed my covenant with the Lord, and prayed for resignation to his Divine will.

But alas!
When it was again required of me to stand up in a meeting and speak the words he bid me,
I again rebelled, and justly incurred the displeasure of my great and good Master.
I went from this meeting in sorrow,
and offered my natural life a sacrifice to be excused from this service,
but it was not accepted; nothing would do but perfect obedience.
In this situation I continued six or seven months;
I could have but little rest night or day, by reason of the anguish of spirit I was in;
yet still longed for meeting days,
and made many promises that if I found the like concern,
and it would please Infinite Goodness to be with me, I would submit to his Divine will,
come what would.
But though I went with these resolutions, when the time of trial came,
I put off the work which was required of me, and came away as before,
full of sorrow and anguish of soul, and knew not what to do;
but often wished myself dead, hoping thereby to be exempt from pain.
Yet not duly considering that if I was removed out of time in displeasure,
my portion would still be more dreadful,
and that it was the old liar who introduced such a thought,
and intended not only to bring me to destruction,
but also to make me the instrument of it myself.

Oh, I have often admired the long forbearance of a merciful God with me;
and when I considered his lovingkindness in preserving me from the devil`'s temptations,
desires were begotten in my soul to conduct through time with reverence and fear,
to his glory.
And here a still more refined snare was laid for me,
which was a conclusion to stay from the meeting, because I believed I might, when there,
disturb the quiet of others;
and really I was ashamed to be seen in the condition I often was in when at meeting.

The Friends with whom I lived, and many neighbouring Friends sympathized deeply with me,
and intimated their concern that I had left off going to meetings, and begged,
as those with whom I lived gave me full liberty to go, both on first and week days,
that I would comply with their request, and go with them as before.
Their arguments had weight with me, and I went,
but had not sat long before the concern to stand
up and speak a few words came powerfully upon me,
with this close hint;
"`this may be the last offer of this kind thou wilt be favoured with, embrace it,
I will be thy strength and exceeding great reward.`"
I then said, "`Lord I will submit, be thou with me, take away the fear of man,
thou shalt have my whole heart.`"
And sitting a while I felt the aboundings of heavenly
love towards God and his people to arise in my soul,
in which I stood up, and after pausing a little, like a child,
spoke a few words which were given me, and sat down in the enjoyment of heavenly life.
The Friends were sensibly affected, and as many said afterwards,
it was a time not to be forgotten.
And so it was to me indeed, for I went home rejoicing,
and renewed my promise of future obedience;
but though I cannot charge myself with wilful disobedience,
yet for fear of a forward spirit I have, I believe, been guilty of the sin of omission.
And though it is dangerous and criminal to withhold the word of the Lord, yet, Oh,
saith my soul, may all who are called to this honourable work of the ministry,
carefully guard against being actuated by a forward spirit which
leads into a ministry that will neither edify the church,
nor bring honour to our holy High Priest, Christ Jesus.
As the tree is known by its fruit, so is such ministry known by its effects,
producing death instead of life; and such as offer this,
will sooner or later sit down in sorrow and condemnation,
for running before the true guide.

About this time the Lord was graciously pleased to renew his merciful
visitation unto the Friends and inhabitants of North Wales and Plymouth;
many of the youth were reached,
and by the effectual operation of Divine and heavenly life,
brought into true submission to the cross of Christ, several were called to the ministry,
and engaged to speak in the authority of the Gospel, which is now, the same as formerly,
the power of God unto salvation, unto all who receive it with meekness,
and truly believe in,
and patiently wait for the inward and spiritual appearance of Christ our holy Redeemer.
Among the many thus favoured,
was our dear and well beloved Friend and brother John Evans,
who was blessed with an excellent gift in the ministry,
and being faithful to his heavenly calling, became an able publisher of the Gospel;
preaching it in the demonstration and power of God.
He was careful to discharge his trust according to Divine ability, yet not forward,
but patient in waiting for the motions of life, by which he attained experience,
and knew when to speak, and when to be silent.
In this, as in his love of silence,
he was exemplary--he was likewise blessed with the Christian virtues of brotherly love,
and universal charity; and being endowed with a good understanding,
was a man of sound judgment; wherefore I always esteemed him as an elder brother,
and gave him the right hand of fellowship.
He was an instrument of help and good to me in my infant state in religion,
which in point of gratitude I ought never to forget.
Oh, may I conduct in such a manner through this state of probation,
as that my latter end may be like his.

Now, though I had in part been faithful to the call of my great Lord and holy Redeemer,
yet he was pleased at times to withdraw the light of his countenance from me,
and to suffer the grand enemy to buffet me severely,
by tempting me to believe that the peace I had enjoyed was only a false one,
that it was all delusion,
that the mortifications I underwent would be of no real advantage to my soul.
Besides he suggested,
how did I know that the Lord required these mortifications at my hands;
that the humility I pretended to, was only feigned,
and therefore the Lord would never accept of it.

Here I was again brought very low in my mind, and my spirit depressed almost to despair;
so that I began to think all this might be true, yet knew not whither to go for help.
But after some time, these words sprang up in my mind, I will trust in the Lord,
for in the Lord Jehovah is everlasting strength.
And then secret breathings arose to God,
that it might please him once more to favour me with his holy presence,
which giveth light and life whereby to distinguish his pure voice from that of a stranger.
But, Oh! the bitter whisperings of Satan, and the thoughts that passed through my mind,
such as my soul hated.
Yet such were the suggestions of the enemy, who was a liar from the beginning.
And indeed,
had not the secret hand of Infinite Goodness supported me through these great temptations,
I should have fainted and lain down in deep despair.

I had not long enjoyed Divine peace, before the old accuser began again,
telling me I had blasphemed against the Holy Ghost, in that I deceived the people,
in pretending to preach by Divine influence, which he insinuated was a positive untruth;
and for me to make a show of worshipping Him whom I had thus belied,
was a sin never to be forgiven.
This was a distressing state to pass through, and lasted several weeks.
I went about mourning like a person almost bereaved of reason;
and though Friends still continued their care and regard to me,
I never had freedom to communicate my exercise to any mortal.
I have since found that the work which the Lord required,
if people would but patiently wait his time, they would be enabled to perform,
and would find deliverance in a proper season.
I concluded I was the worst creature ever born,
and had only received life for Divine vengeance, but the Lord gave me to see otherwise;
for sitting one time alone in the woods, a cry rose up in my heart,
if I die it shall be at thy foot-stool,
O Lord! for thy lovingkindness has been great to me from my youth to this day;
and falling on my knees,
I prayed that he would be graciously pleased to enlighten
my understanding in such a manner,
that I might see clearly wherein I had offended so merciful a Father;
for I thought I had offended him, because I was suffered to be so tempted.
His word then became as a fire in my breast,
and the answer I received was to this effect; be encouraged,
thou art suffered to pass through these trying dispensations,
not only on thy own account, but for the sake of others to whom, when qualified, I will,
in my own time, send thee: be faithful, and I will be with thee to the end of time.
At this intimation I was tendered and filled with gratitude to his Divine Majesty,
who alone can deliver his children out of their afflictions.

My soul at this time, under a sweet sense of his goodness,
bows in awful reverence with praises to his holy name, and says,
Who is like unto our God!
I wish all who make profession of the Truth may conduct
agreeably to the holy principle of sincerity,
and then such will be good examples to their children and families, if they have any,
as also to the youth in general.
There were many incidents occurred during the time of my being among those Friends,
to whom I was indented for payment of my passage, which for brevity`'s sake I omit.
When the time for which I engaged to them was expired,
I served them a quarter of a year longer,
in consideration of the tender regard they had shown to me,
when it was in their power to have conducted otherwise,
and for granting me the liberty of going to week-day meetings;
which they accepted from me with reluctance.

We loved one another much, and being unwilling to part,
I stayed with them till the spring,
and then in much love and tenderness we parted.--I am persuaded that if servants
were careful to discharge their trust faithfully to their masters and mistresses,
the Lord would provide suitably for their support through the world,
with credit and reputation.
I never was more easy and contented in mind, with regard to outward things,
in any station of life, than when I was a servant; because under this circumstance,
I met with that for which I had laboured many years,
the true and saving knowledge of Christ Jesus, who is the only way to the Father,
and whom to know is life eternal.
I cannot but desire that people in every condition in this world may be thus blessed.
When the soul is tendered with the love of God,
it strongly desires that all may be partakers of life and salvation,
as freely offered through Christ Jesus our Lord.

When I had fulfilled my contract as above, I found a concern to remove over Schuylkill,
which I did, with the advice of some of my Welch friends,
who had been as nursing fathers and mothers to me.

I stayed some time at Haverford, where I found many good Friends who were tender of me.
I attended meetings diligently, both on first, and other days of the week, at Haverford,
Radnor, Merion, etc., as I found freedom; yet I very seldom appeared in public.
When out of meetings I kept myself pretty much retired from company,
finding retirement profitable for me in this my infant state in religion.
I hired for a month with a Friend, but would not engage for a longer time;
because I found this was not the right place for me to settle in.
I was scrupulous of fixing any price for my work, fearing I might overvalue it,
and those for whom I wrought would lose by me;
therefore I left it to them to give me what they thought
I earned.--Thus I conducted to the best of my understanding,
with fear, lest I should bring dishonour to the holy profession I made,
and be a stumbling block in the way of tender inquirers.
The Lord regarded me in this state,
and not only favoured me many times with the descendings of heavenly life and love,
but gave me favour both with Friends and others,
so that I might have had the best places either in Philadelphia or in the country,
but I was not to settle in those parts.
I must go a little farther, but the place was still hid from me.

One first-day, after I had sat some time in Haverford meeting, David Lloyd from Chester,
with his wife and several other Friends, came into meeting.
As soon as they were seated, it was as though it had been spoken to me,
"`These are the people with whom thou must go and settle.`"
They being strangers to me, and appearing as persons of distinction, I said, Lord,
how can such an one as I get acquaintance with people
who appear so much above the common rank.
The word was in my soul, be still,
I will make way for thee in their hearts--they shall seek to thee.
I knew not what to think of this, and was afraid it might be a temptation of Satan;
yet was contented in the thought, that the Lord who never yet failed,
was all-sufficient to provide for me.
At that instant a great stillness came over me,
and I felt the love of my heavenly Father to affect me in a very uncommon manner.
I afterwards understood that David Lloyd and his wife fixed their eyes upon me,
felt a near sympathy with me, such as they had never known towards a stranger before,
and said in their hearts, this young woman is or will be a preacher.
They were both tendered, and it was fixed in their minds,
that they were to take me under their care, and nurse me for the Lord`'s service,
with a promise that his blessing should attend them.
This I had from their own mouths after I lived with them.

After the meeting I was passing away, as usual, for fear of being taken notice of,
but was stopped by a Friend, who asked me to go home with her,
for the Chester Friends were to dine there.
I excused myself as well as I could; then those Friends came and spoke kindly to me,
which affected me in such a manner, that they let me go, but told some Friends there,
how they were affected towards me, and how it opened to them in the meeting.
They left their love to me,
and said they intended to visit me soon with proposals for living with them;
for by what each of them felt in themselves, they were to be instruments of good to me.

Soon after this I became acquainted with Elizabeth Levis, a Friend of Springfield;
the manner of which was thus.
I had not appeared in public for a great while, nor felt any motion that way,
but was very low in my mind, and having got into a dark spot, had again almost lost hope,
and thought it impossible but that I should fall
a sacrifice to the temptations of the grand enemy,
who still followed me.
However, it happened that Elizabeth Levis came to visit Haverford meeting,
where I then was.
After some time of silence she stood up, and speaking in the authority of Truth,
so effectually laid open my present state,
that I could heartily subscribe to the truth of the testimony.
The power that attended her ministry reached the witness of God in my heart;
a zeal was begotten in me for the honour of the good cause;
and I was filled with love to the instrument through whom I had thus been favoured.
Hope was again renewed in me by virtue of the word preached,
that the Lord would still continue his wonted favours to me,
in preserving me from the snares of the wicked one.
After meeting she took kind notice of me, and said, I came here today through the cross,
the Lord knows for what end; it may be for thy sake.
I was so overcome I could not speak, but wept much,
and esteemed it as a blessing she had taken notice of me.
I went home rejoicing in spirit, because I had met with Divine refreshment,
of which I was in much need.

As it pleased the Almighty to visit me in a wonderful manner,
by the renewing of his pure love, I made covenant,
that if he would be with me in the way I should go, he should be my God,
and I would serve him forever.
This disposition increased,
and I felt the unity of the one spirit with this dear hand-maid,
in which we became near and dear to each other,
and in process of time joined as companions in the work of the Gospel,
as I shall hereafter have occasion to mention in the course of this account.
But to return, my mind was still engaged about Chester,
with strong desires to be with Friends there, but how to accomplish it, was the question.
I knew the promises of God, were yea, and amen,
and in this I confided--but a good opportunity soon offered.

I was just finishing some work which I had taken to do for a Friend, and on my saying,
when this is done, I know not where to get more--one, not of our Society,
being in company, said to me, "`Fear not, God will always provide for you,
because you fear his great name.`"
I made no reply, but in a few minutes a person knocked at the door; I being next to it,
opened it; when I saw a man of a good appearance, sitting on horseback,
who asked if there was a young woman there who wanted a place, for he wanted a maid,
one that was sober?
We desired him to alight, and inquired of him, whence he came?
He and his family belonged to Chester meeting, and he lived not far from the town.
It immediately started into my mind, it may be this is a providential thing,
to bring me to that people; I will give him expectation of my going with him next week,
if he will come for me, but concluded to hire only for a month,
to see how I liked his wife, etc.
I communicated my mind to him; he accepted, and inquired what wages I asked?
I answered as usual, what they thought I deserved, and we parted.
His name was Benjamin Head, a worthy, honest man.
He called at a Friend`'s just by, and told of his success, and when he was to fetch me;
they said I was a preacher, and they were unwilling to part with me; but he had my word,
and came according to our agreement: I was prepared to attend his call,
and so went with him.

I found his family were only himself, his wife and daughter,
with one man and a maid servant: his wife being apprised of my character,
received me with love and affection, which lasted, not only while we lived together,
but to the conclusion of their time in this life.
Indeed, it would have been high ingratitude in me,
if I had not returned their kindness in the best manner I could;
for I had not been there three weeks, before I was seized with a violent fever,
which reduced me so low, that my life was despaired of,
though they got the best advice that could be had, sparing neither cost nor labour,
in hopes of restoring my health.
The distemper was violent on my body, yet I was favoured with quietude of mind,
and entirely resigned to the Divine will, whether to live or die.
It is a great blessing which attends those who fear God,
that his holy spirit accompanies their souls, when upon a bed of languishing:
the Psalmist experienced this in his day, and so will all the righteous now,
as well as then.
This illness held me near three months, in all which time Benjamin Head`'s wife,
and her daughter, a sober young woman, attended me night and day very carefully.
Several Friends of Chester and others visited me,
and tendered their services in ministering things suitable for my disorder and otherwise;
so that I wanted for nothing proper for me.
Some Friends were for removing me, but that was impossible; besides,
the Friend with whom I was, objected to any such measure, and I was against it myself,
under this consideration, that if it pleased Providence to raise me,
it would be my duty to stay and make such return
for their kindness as might be in my power.
Thus the time was prolonged six or seven months instead of one,
so that we poor short-sighted mortals may propose many things to ourselves,
but Providence can disappoint, and all for our good, if we patiently submit;
and indeed it is our interest so to do.
Grace Lloyd perceiving that Benjamin Head`'s wife was unwilling to part with me,
forbore speaking anything of her mind to me till after I had got out to meeting,
which I did as soon as I was able.

My first going to meeting was on a first-day; the meeting was large,
by reason that John Danson, a Friend from Great Britain, was there.
I sat about the middle of the house, under great exercise of spirit,
insomuch that the Friend was sensible of it; though I did not appear in testimony,
yet I was not hid.--I do not remember anything remarkable that attended the meeting.
John Danson was silent; and as soon as it broke up, he spoke to David Lloyd, saying,
"`Stop that young woman, who sat in such a place,
I have something to say to her from the Lord.`"
He spoke aloud; I heard him, and trembled, and was going away;
but Grace Lloyd desired me to stay, and kindly told me, I must go home with her.
I excused myself: but it did not do, she would not be denied, I must go.
I therefore asked leave of my employer`'s wife, which she readily gave,
and left a horse for me to ride home.

When we came to David Lloyd`'s, there was a great company of Friends;
but not thinking myself worthy, I would not thrust myself among them,
intending to go among the servants.
This was not permitted, for as I was entering the parlour,
I heard the English Friend say, "`Where is the young woman, I want her company.`"
I came in, and was seated next to him.
He took hold of my hand, fixed his eyes upon me,
and after a little silence spoke to me in such a manner, by way of encouragement,
as I have not freedom here to relate; only so much I may say,
he proved a true prophet to me, as I afterwards experienced,
respecting the work the Lord was preparing me for, and about to employ me in.
But I, like Nicodemus, was ready to say, how can this be;
will the Almighty engage a poor unworthy creature in so great a work?
he knows I am noways sufficient for the task.
The Divine word to me was, "`Trust in my sufficient power,
that shall properly qualify thee for every service.
What I require of thee is to be faithful,
and thou shalt see greater things than yet have been made manifest.`"

I felt Infinite Goodness near;
my soul bowed in awful reverence to the Divine Majesty of heaven and earth;
and in the secret of my heart I said.
Lord, I will submit to every dispensation thou allottest.
The Friends present were mightily broken,
and we were made partakers together of the virtue of light and life,
which caused gladness of heart, so that little food satisfied some of us.
After dinner, the Friend spoke to David Lloyd and his wife, saying,
"`Take this young woman, make her your adopted child,
and give her liberty to go wherever Truth leads.`"
They told him, that was their intention, and when I was free to come,
their house should be my home for the future.
He replied, "`Do as you say, and the blessing of God will attend you on her behalf.`"
Grace Llovd then took me into another apartment,
and told me how she and her husband were drawn in
love to me the first time they saw me at Haverford,
as is related; and if I would come and live with them, they intended to do well for me.

I admired at the ordering of Providence, in thus providing for me,
a poor destitute orphan, separated from all my natural friends, in a strange land,
and having no certain habitation in mutability.
Oh! that all would fear and serve the living God, whose goodness endures forever;
it was his own work, and he shall have the praise.
We parted in tears, under the holy influence of Divine love,
and with a sense of his wonderful kindness to me, I went home rejoicing in spirit,
praising the Almighty.
I mended fast as to health,
so that I was able to perform to the satisfaction of my master and mistress;
with whom I stayed till near spring, and then parted in much affection.
We loved each other sincerely: they always treated me with respect, as I did them,
being fully satisfied they were instruments in bringing
me to my future settlement in this world;
and this love subsisted between us until it pleased the Lord to take them to himself;
their memory is as agreeable to me now, as in the beginning of our acquaintance.

I entered into David Lloyd`'s family as an upper servant, such as we call in England,
house-keepers, having all the keys, plate, linen, etc., delivered to me.
They had a great family, and everything passed through my hands;
and as they had reposed such a trust in me, it brought a weighty concern on my mind,
that I might conduct aright,
and discharge my duty faithfully to my principals and their servants;
and being sensible of my own weakness, I many times, when others were asleep,
poured out my prayers to God for wisdom, who giveth liberally and upbraideth none.
I was often afraid lest through my misconduct,
I should bring dishonour to the pure Truth I made profession of;
for now I began frequently to speak in meetings, and many eyes were upon me.
I was become like a city set on an hill which could not be hid;
and Christ our Lord speaking of this situation, says, "`Let your light so shine,
as that others beholding your good works, may glorify your Father which is in heaven.`"
This text was often revived in my memory;
and under this dispensation I was led through a painful anxious travail of soul.
I considered that I had been tried in low life,
though I never wanted for any necessaries, but was always provided for,
having met with kind treatment from all sorts of people,
and was blessed with contentment in the station allotted me.
Now I was to be proved with greater plenty,
and favoured with the company of valuable Friends, who often frequented our house;
and though I was but in the station of a servant, yet was taken notice of by them;
for when they came, I was always allowed to be in the room with them.
This was a great favour conferred on me, and it did not elevate my mind,
but made me more humble and assiduous in my business.
Another kindness extended to me was, that I always dined with my master and mistress,
which was of advantage to me, for many times their conversation was profitable.

Thus as I kept my eye steady to the Almighty, he gave me favour among my friends,
and with both my said benefactors, and they were kind and affectionate,
like tender parents, watching over me for good,
often telling me to mind the dictates of Truth;
and if at any time I found a concern to visit any meetings, be sure to go;
and they were careful to provide suitably for me in every respect.
This was engaging, and my love to them increased daily;
I judged it my duty to make their interest my own, as if I was their child,
and can in truth say, I never willfully disobliged either of them,
or left their service to serve myself, in any shape.
I went nowhere without their leave, not so much as to buy any trifles I wanted;
and when a religious concern came over my mind to visit the churches of Christ,
they were the first whom I made acquainted therewith.

The first visits I made were to some of the neighbouring meetings,
in company with some of our friends, and returned at night;
afterwards it became a concern upon my mind to visit Friends at Philadelphia,
and some more meetings in that county, in the company of a Friend from Long Island.
I had my friends`' leave to go this journey, and went with her into Bucks county;
from thence I returned home, and was diligent in my business when there;
for though the Lord was pleased to crown my labours in the ministry with success,
and Friends everywhere were exceedingly kind to me, yet I was not exalted,
being sensible that of myself I could do nothing that tended to good.
I therefore found it my business to return unto the place of waiting,
to know the further will and pleasure of my great Lord and Master, Jesus Christ.
But though I enjoyed satisfaction and peace, of which the world could not deprive me,
and met with abundance of love and respect from Friends and others,
yet I was not exempted from the buffetings of Satan, within and without,
nor from the woe pronounced by our Lord against those whom all men should speak well of.
I had outward enemies who wailed for my halting, but blessed be the Mighty arm of Power,
it supported me through all,
and preserved my feet from falling into the snares which were laid for me.
How invaluable is the light of Christ! it manifests the wiles of sin and Satan,
so clearly, that some have reason to say,
surely in vain the net is spread in the sight of any bird.

In the year 1714, our worthy Friends Thomas Wilson and James Dickinson,
came into this province, on a religious visit to the churches.
I was present at a meeting they had at Plymouth,
which on account of the great gathering of people, was held under the trees.
Thomas, in the exercise of his gift, was led to treat on several subjects,
which making a great impression on my mind, at that time,
and tending to confirm me in the faith I made open profession of, I still remember.
He was led to speak of David`'s bringing the ark of the Lord from the house of Obed-Edom;
also the festival, a sacrifice he offered to the Lord, and his dispensing the bread,
flesh, and wine to the multitude, to the women as well as the men;
which Thomas repeated two or three times,
from thence inferring the Lord`'s influencing females, as well as males,
with Divine authority, to preach the Gospel to the nations.

He spake largely on the passage of the captive maid,
and her service to her lord and master;
and in a powerful manner set forth the privileges which the true
members of the church of Christ enjoy under his peaceable government.
He also spake prophetically concerning the work of sanctification which some were under;
saying, the Lord would bring the faithful through all to his glory,
and the solid comfort of the afflicted, though some might be like David,
in the horrible pit, etc.
These and divers other subjects which he mentioned, greatly affected me,
and reached me in such a manner, that I was much broken, and said in my heart,
surely all here will be not only convinced, but converted by the eternal Word of God,
unto the true faith of Christ our Lord,
who came to seek and to save all who should believe in his pure name.
I thought none could withstand the doctrine preached,
it being with great power and Divine authority,
not as that of the scribes or hireling priests.
What made it farther remarkable to me was, that the Friend where they dined,
insisted on my going with them, and it being in my way home,
with fear and trembling I complied, and being sat down in the house,
Thomas Wilson fixed his eyes upon me,
which made me conclude he saw something in me that was wrong.
I arose and went out, being much affected, but heard him say,
"`What young woman is that?--She is like the little captive maid I have
been speaking of this day.--May the God of my life strengthen her;
she will meet with sore trials, but if she is faithful,
the Lord will fit her for his service.`"
He further remarked, that he saw the Lord was at work in me for good,
and would in his time bring me through all.

These hints have since been of service to me, when almost overwhelmed in trouble,
and I think should never be forgotten.
I do not mention them in ostentation, but bow in awful reverence,
as with my mouth in the dust, rendering to the great Author of all our mercies,
adoration and praise; may it now be given unto Him, and forever.
Amen.

It was in the year 1710, I came to David Lloyd`'s,
but did not travel far abroad until the year 1722, when having the consent of Friends,
and their certificate for that purpose, between that time and the year 1725,
I accompanied my before-mentioned friend Elizabeth Levis,
on a religious visit to Friends in Maryland, Virginia, and North Carolina.
Returning home, we afterwards went to Barbados,^
footnote:[In looking toward this extensive and arduous journey,
they met with some discouragements which were trying to their feelings,
and the following letter was addressed to them by Thomas Chalkley,
an eminent and experienced minister of Christ.
It should be observed, that Jane Hoskens`' maiden name, was Fenn.
He says; --
{footnote-paragraph-split}
In this year two sober young women,
Elizabeth Levis and Jane Fenn,
were concerned to visit Friends in the island of Barbados,
and they meeting with some discouragement,
in Christian love I wrote them the following letter,
to encourage them in the work of Christ, viz:
{footnote-paragraph-split}
Frankford,
1st of twelfth month,
1724-5.
{footnote-paragraph-split}
My dear friends,
{footnote-paragraph-split}
Elizabeth
Levis,
and Jane Fenn,
{footnote-paragraph-split}
Understanding by our friend, Grace Lloyd,
that you have proposed your intention of visiting the few Friends in the island of Barbados,
and that you meet with some discouragement inwardly and outwardly,
it is in my mind to comfort and strengthen you in so great and good an undertaking,
and honourable work, as is the cause of Christ, who, for our sakes,
crossed himself abundantly beyond expression,
more than is possible for us to do for his sake, or the sake of his people,
whom we may so entirely love, as to lay down our lives for his and their sakes.
But what are our lives to the life of the only begotten Son of God?
And truly, we must give them up often, if we have the cause of souls at heart;
and then he often gives them to us again, glory to his holy name forever!
As Christ said, He that will save his life, shall lose it,
and he that will lay down his life for my sake and the Gospel, shall find it;
which reacheth your case in this undertaking.
And, indeed, some of our lives, in our own sense, are hardly worth mentioning,
considering the cause of Christ.
{footnote-paragraph-split}
And, dear children of our heavenly Father, I may,
through some good experience, truly inform you,
that there is much openness in many people on that island,
and good encouragement I have had, from above, in my visiting the people there; though,
true it is, the inhabitants, too generally, are luxurious, and much given to vanity:
yet I have this seal in my heart,
that the Lord hath a seed in that place who desire to serve him,
and that seed will surely join with you in your exercise,
and you will be comforted one in another, and in the Lord.
And that there are differences among them, is also true;
but they have the more need of being visited by such, who are,
through their wise conduct and restoring disposition,
likely to heal those breaches which are, or may be among them.
Some, indeed, have gone among them and have done hurt,
by a rash and turbulent management, and by so doing, have rather made the breaches wider,
than by a meek and loving, as well as lowly disposition,
lessened their differences and healed them.
{footnote-paragraph-split}
And, tender friends,
though it may seem hard for you in several considerations, to give up to go to sea,
and also to divers who love you and are nearly related to you, know ye,
and such so concerned, that the Lord is stronger than the noise of many waters,
and than the mighty waves of the sea.
And I really believe that you, as well as my soul, with all the servants of Christ,
will experience it to be so, as David did,
whose words they are.
{footnote-paragraph-split}
I
remember the words of our great Lord and Master,
Jesus Christ, when he sent forth his servants to preach his Gospel;
'`I send you forth as lambs among wolves.`' No question but you, like innocent lambs,
before your return, if it please God to give you to us again,
may meet with the wolf`'s spirit, or the spirit of the beast,
in some among whom you may travel; then will the counsel of Christ,
added to his commission, be good for you to keep close to: '`Be ye wise as serpents,
but innocent or harmless as doves.`'
{footnote-paragraph-split}
And, dear maidens,
as your cross is great, you being two innocent young women,
in giving up your names to cross the sea, which I know is a great trial, the seamen,
too generally being rude, dissolute people; so your crown will be great also.
I have known that by keeping near to Christ and his truth and power,
there hath been a wonderful reformation sometimes in several of those rude seamen;
and some have been so far convinced, as to be exceedingly kind,
and to speak well of Friends and their conversation,
when it has been coupled with the fear and wisdom of God.
When I have gone to sea, I always found a religious and Christian concern upon me,
for the poor sailors, the good effects of which have been much more than I may speak of;
but give this little hint for your encouragement and information.
{footnote-paragraph-split}
Well,
dear souls, if you go, I believe the Lord will go with you; and sure I am,
that my spirit will also go along with you, which will not hurt you,
if it do you no good.
And although my exercises and tribulations of late have been very great,
both spiritual and natural, yet my very heart within me affects the cause of Christ,
according to the best of my understanding;
and I heartily wish well to all my fellow-labourers, who are faithful,
painful servants of Christ, and disinterested,
except as to the interest which they desire in Christ and his kingdom,
for the sake of which,
they love not their lives unto death.
{footnote-paragraph-split}
I must now take leave,
after putting you in mind to remember your poor friend and brother,
when before the throne you are supplicating the Father of mercies in secret,
even as my heart is tenderly bowed and broken into tears on your behalf at this time.
The Lord be with you, and sanctify the present exercise and concern that is upon you,
and you to himself, with all the faithful lovers and followers of the Lamb,
'`through his word, whose word is truth.`' I am your friend and brother,
in the fellowship of the Gospel of Christ Jesus, our great Lord and good Master;
and blessed are all those, who, by their fearing to offend him,
manifest him to be their Master,
and by their honouring him manifest him to be their
Lord.
{footnote-paragraph-split}
Thomas Chalkley.]
and from thence took shipping and landed on Rhode Island, and visited that place,
Nantucket, New England, Long Island, the Jersies, our own province,
the counties of New Castle, Kent, and Sussex on Delaware, the eastern shore of Maryland,
and again into Virginia.
It was in the year 1725, that we visited Barbados,
in all which journeys and voyages we were true yokefellows;
sympathizing with each other under the various exercises whether of body or mind,
which we had to pass through.

Elizabeth was sound in the ministry, and wherever we were led,
she was of great and good service.
I always preferred her for the work`'s sake; her conduct out of meetings was exemplary,
and preached aloud.
I must add, she was no busy-body; we meddled not with other people`'s concerns,
whether in or out of meeting.
She was of great service to me,
and I hope the love which subsisted between us when young,
will remain to each other forever; mine is now as strong to her as then,
for which I am truly thankful to the Author of all goodness.

In the year 1726, I travelled with Abigail Bowles, from Ireland,
through the lower counties on Delaware, the eastern shore of Maryland, Virginia,
Cape May, the Egg Harbours, and other parts of New Jersey, and through this province;
in which journeys we travelled about one thousand seven hundred miles.
Having had a concern in the love of Christ, for a considerable time,
to visit the churches in Great Britain, Ireland, etc.,
I acquainted Friends in our parts with it,
and had their concurrence and certificate for that purpose.
On the 13th day of the third month, 1727,
in company with our dear Friend Abigail Bowles aforesaid, and several others,
I went on board the ship __Dorothy,__ John Bedford, commander, bound for Bristol;
there being but little wind, we did not leave the capes of Delaware till the 20th,
and on the 27th of the fourth month landed safe at Bristol.
We held our meetings in the great cabin, during the voyage, when the weather permitted,
which the Lord was graciously pleased to own with
his life-giving presence to our comfort and satisfaction;
for which and all his tender mercies and preservations he shall have the praise,
who alone is worthy.
We were kindly received by Friends at Bristol, and lodged at Richard Champion`'s.

Twenty-ninth being first-day,
I was at their Quarterly Meeting of worship for young people;
and the first of the fifth month I parted with my dear friend Abigail Bowles,
she going homeward in a ship bound for Cork, in Ireland, and I stayed at Bristol.
The 31st of the fifth month I got to London,
having meetings almost every day after my landing, and generally to satisfaction.
I stayed in and about London, visiting meetings and Friends,
till the 6th of the seventh month, when I left that place,
and travelled through divers parts of the nation, visiting meetings as my way was opened,
in which services the good hand of my great Lord and Master was near,
and supported under many close trials and deep baptisms.
Indeed, I may say,
he was pleased at times to furnish his minister with suitable
doctrine to the states and conditions of the people,
so that many were reached and confessed to the Truth,
the mouths of gainsayers were stopped,
and the upright-hearted encouraged to persevere in the way of Truth and righteousness.
It was a gathering day in many places:
May the great Lord of the harvest so operate on the minds of the people,
by his eternal power and spirit,
that many may be rightly qualified for his work and service,
to the glory of his holy name!

On the 14th of the second month, 1728, I came to Whitehaven,
and on the 16th went on board the ship _Reserve,_ John Nicholson, master, bound for Dublin,
in Ireland,
where we arrived safely on the 18th. I was at most of the meetings in that kingdom,
had meetings in many places where no Friends lived,
and visited Friends in their families, within the city of Dublin.
In many opportunities which I had, both among Friends and others,
it evidently appeared that Divine counsel was unfolded to the people.
The doctrine of Truth descended as the small rain upon the tender grass,
whereby many were refreshed, and a living greenness appeared.
Many of other societies were tender, and well satisfied with the visits,
and some among them appeared ripe for information respecting Friends`' principles;
so that the faithful had frequently cause to rejoice in the wonderful condescension
and lovingkindness of the merciful Creator of heaven and earth,
from whom all good comes.

On the 19th of the seventh month, 1728, I embarked from Dublin,
and on the 20th landed safe at Grange, in Lancashire.
After I had visited many places in this nation,
and spent a considerable time in travelling therein to good satisfaction;
finding myself clear of the service in this part of the world,
I embarked again for America, where I arrived the 13th of the twelfth month, 1730,
and was affectionately received by my kind friends and benefactors,
David and Grace Lloyd, and other Friends here away.

Soon after my arrival David Lloyd was taken ill with his last sickness,
during which I thought it my duty to attend on him as usual.
On the 6th of the second month, 1731, he departed this life; and in him I lost a father,
and a sure friend.
In all the journeys I went, whilst he lived,
he cheerfully supplied me with the necessaries requisite.
He was exemplary in his family, treating all about him with humanity,
choosing rather to be loved than feared.
He was diligent in attending meetings for worship,
and those of his servants who inclined to go to meetings,
he allowed to perform that necessary duty.
After my arrival I did not live as an hired servant with David Lloyd, or with his widow,
though I remained with her, at her request, till I married, which was in the year 1738.

In the year 1742-3, I went a second time to Barbados, in company with Rebecca Minshall;
from Barbados we took shipping for Rhode Island, and visited that place and New England.
In the year 1744, I had a certificate to go a second time to Maryland,
Virginia and Carolina, in company with Margaret Churchman;
concerning which visit I could say much, but it may suffice to remark,
that it appeared to me to be a time of gathering,
and great openness among people of various ranks.
They followed us from meeting to meeting, treating us with respect,
and the marks of real love and affection;
but knowing we had nothing valuable of ourselves, I attribute all to Divine Goodness,
who opened the way for us, and is alone worthy.
Margaret sometimes appeared in public, and I thought to good purpose,
and was to me a good companion.

In the year 1747,
I performed a second visit to the churches of Christ in England and Ireland.
I had hitherto undergone many close trials and provings in my pilgrimage through life,
but this visit was attended with some of the heaviest and
most painful exercises of any I had ever before experienced.
Yet I have to believe the good hand, though often concealed, was near under all,
and the Lord enabled me at times to speak to the conditions of the people,
so that the witness was reached,
and by his own Almighty power the seed raised and brought into dominion.
Of this, time hath brought undeniable proofs,
so that though this was a painful journey both to body and mind,
yet as the infinitely wise Being was pleased to bless it to some,
to the honour of his own great name, I dare not repine,
but hope humbly to submit to what he hath permitted,
or may permit to attend for the refining of my faith, and making it more pure than gold.

In the year 1756, with the concurrence of Friends, and their certificate,
having my friend Susannah Brown of Philadelphia, for my companion,
I performed a visit to Friends in New England, etc., as far as I was enabled to travel,
though we did not go further eastward than to Salem.
We had several satisfactory meetings among Friends and others.
We first went to New York, and had a meeting there, Friends being glad of our company,
which they manifested by their respectful conduct.
In company with several of them we went to Long Island,
and attended the Yearly Meeting at Flushing,
which was large and favoured with Divine authority from day to day.
The people behaved with commendable stillness and quiet,
and many Friends remarked it to be more so than usual,
the Lord manifesting his power through poor weak instruments.
From thence we proceeded by water to Rhode Island,
several Friends of New York accompanying us,
and arriving there about a week before the time of their Yearly Meeting,
we had a seasonable opportunity of resting,
being received by Friends with great kindness.
Through Divine favour we were enabled to go through
our service at the said meeting to great satisfaction,
being comforted in spirit in a sense of Divine goodness,
and I hope bowed in awful reverence unto Infinite mercy in a suitable manner.
After this meeting we went to Tiverton, where we had three meetings,
which I think were large and satisfactory.

From thence we took passage in a sloop for the island of Nantucket,
where we attended the Yearly Meeting, which was large and to good satisfaction.
In going ashore from the sloop I received a hurt, which proved very painful,
yet I attended the meetings every day,
and was qualified to go through the service required,
which I looked upon as a great favour.
We stayed two weeks at this island, and then, with Sylvanus Hussey and his son,
embarked on board their sloop for Boston, where we were detained eight or nine weeks,
on account of my lameness, being unable to travel.
Friends of the place were exceedingly kind, and I must in justice remark,
that people of other societies were also, insomuch that I was made to admire;
but it was the Lord`'s doing, and not any merit of mine.
When I got out to meetings they were crowded,
the people continuing to carry with much respect towards us; and when we left that town,
several accompanied us on the way, and some, not of our community, went to Rhode Island,
and were at all the meetings with us, which were large and crowded,
and I have reason to conclude satisfactory;
when we took leave of each other it was a time worthy to be kept in remembrance.

We came to New York, and from thence passed over to Long Island,
visiting most of the meetings thereon; and after the last appointed for us,
I was seized in a very uncommon manner, my understanding being so clouded,
I could not recollect where I was, yet was blessed with quietude and peace,
fully resigned to the Divine will.
In this condition I was taken to Flushing, where I lay some days;
and although thus afflicted, in the intervals when my reason returned,
the peace I enjoyed, and the sweet assurance of my being right in going this journey,
was such as I never felt before, which bowed me in reverence before the Divine Majesty,
saying, Lord, it is enough.
It was the fourth visit I had paid to New England, and likely to be my last;
and the mighty power of God was more conspicuously manifested to my soul,
than I had known after any other journey.
Several Friends from New York accompanied us to Amboy, where we parted in much love;
we came to Bordentown,
where we stayed several days and had a meeting which was satisfactory,
though attended with hard labour, before the rubbish was removed;
I was favoured and clear in my understanding.
Friends accompanied us over the river to Pennsylvania,
and Ennion Williams meeting us there, I was conveyed in his carriage to Bristol.
Stayed the first-day meeting at that town, several Friends from Burlington being at it,
we were mutually comforted in each other,
in the immortal love and life which our heavenly Father favoured us with.
Herein we parted, and that afternoon came to Philadelphia, where we stayed a few days.
Here my companion and I parted in love, as we had travelled together;
she being kind and very affectionate to me,
and was I believe of service in the course of our religious visit.

I have thought how the wisdom of Divine Goodness
is eminently displayed through Christ our Lord,
in sending forth his servants to preach the glad tidings
of the Gospel of life and salvation to the people freely.
I am persuaded,
where companions in this solemn service are firmly
united in the true bond of Christian fellowship,
it must tend to confirm the authority of their message,
testifying their joint consent to the doctrines they teach, to comfort, strengthen,
and support each other, through the many trying dispensations,
which in the course of their travels they have to wade through; this being the real case,
judge how great must be the disappointment, when it happens otherwise!
May the all-wise God be pleased to visit those who have gone out of the right path,
which by virtue of his light he had graciously led them into,
and restore them into his favour, that their latter end may be rest and peace forever!
The rest of my time after my return home from this journey,
was principally spent in attending our meetings,
and although my infirmities and troubles were not few,
yet I have been helped wonderfully through, therefore must not repine.

In the fifth month, 1760, my worthy friend Grace Lloyd, departed this life.
She was one who was favoured with excellent talents,
and in the early part of her days was reached to by the almighty hand of God;
and as she yielded obedience to the dictates of his Holy Spirit,
became serviceable in the church of Christ, had a good gift in discipline,
and many times spake in these meetings by Divine authority,
to the tendering of many hearts.
She was a woman of good understanding, sound judgment, and quick apprehension;
and I hope is reaping the peaceable fruits of righteousness.
Thus much I thought in gratitude I was obliged to hint concerning her;
and when I look back and consider how the Lord was pleased
to influence the hearts of his people in love towards me,
when absent from all my natural friends, I can but admire his unmerited mercies,
and say he is worthy of worship and pure obedience; for who is like to our God.

I might have added in the course of the foregoing short narrative,
that I attended several Yearly Meetings at Philadelphia,
and although I was of little or no service, yet I always returned home better,
having enjoyed among my dear friends that consolation which my soul thirsted after.
Upon the whole, I may say as did king David, Ps. 19:2,
"`Day unto day uttereth speech,
and night unto night showeth knowledge;`" by sore afflictions we learn experience,
and if we make a proper use thereof, all will in due time be sanctified to us,
so that we shall receive the word of instruction with joy.

[.signed-section-signature]
J+++.+++ H.
